// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzRKho-g0RgNz7qu8b3QrwlR087O7xKo',
    appId: '1:248140694812:web:a68d7882b2f5e91ea8a6d9',
    messagingSenderId: '248140694812',
    projectId: 'animal-suvidha-25cea',
    authDomain: 'animal-suvidha-25cea.firebaseapp.com',
    storageBucket: 'animal-suvidha-25cea.appspot.com',
    measurementId: 'G-8J7JEXN5JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHTsIDvskpCKTfgApkZJoiAVm6KSNGU-U',
    appId: '1:248140694812:android:68522384fca4755ba8a6d9',
    messagingSenderId: '248140694812',
    projectId: 'animal-suvidha-25cea',
    storageBucket: 'animal-suvidha-25cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ORSs4sXqGL6QURkNtsPKaIzjPnGOCZM',
    appId: '1:248140694812:ios:9aafd8b93d139fdda8a6d9',
    messagingSenderId: '248140694812',
    projectId: 'animal-suvidha-25cea',
    storageBucket: 'animal-suvidha-25cea.appspot.com',
    iosBundleId: 'com.example.animalSuvidha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ORSs4sXqGL6QURkNtsPKaIzjPnGOCZM',
    appId: '1:248140694812:ios:9aafd8b93d139fdda8a6d9',
    messagingSenderId: '248140694812',
    projectId: 'animal-suvidha-25cea',
    storageBucket: 'animal-suvidha-25cea.appspot.com',
    iosBundleId: 'com.example.animalSuvidha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTzRKho-g0RgNz7qu8b3QrwlR087O7xKo',
    appId: '1:248140694812:web:2e7e8b8a3de2b5e3a8a6d9',
    messagingSenderId: '248140694812',
    projectId: 'animal-suvidha-25cea',
    authDomain: 'animal-suvidha-25cea.firebaseapp.com',
    storageBucket: 'animal-suvidha-25cea.appspot.com',
    measurementId: 'G-775PCFCGCV',
  );
}
